services:
    mylib.tmdb_api:
        class: AppBundle\Services\TmdbApiServices
        arguments: ["@wtfz_tmdb.client"]

    mylib.twig.mylib_extension:
        class: AppBundle\Twig\MylibExtension
        tags:
            - { name: twig.extension }